name: udid
description: Flutter plugin get device udid.
author: Lewis <once10301@gmail.com>
homepage: https://github.com/once10301/udid
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ly.udid
    pluginClass: UdidPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.1.4 <2.0.0"